{
    "spreadsheet_id": "required_value",
    "names_conversion": "optional_value",
    "credentials": {
        "auth_type": "optional_value",
        "client_id": "optional_value",
        "client_secret": "optional_value",
        "refresh_token": "optional_value",
        "service_account_info": "optional_value"
    }
}